name: Block Direct Push to Main

on:
  push:
    branches:
      - main

jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if push is not a PR merge
        if: ${{ !contains(github.event.head_commit.message, 'Merge pull request') }}
        run: |
          echo "Direct pushes to main are not allowed. Use a pull request."
          exit 1
